#!/bin/bash
#
# Apply recommended SmartOS TCP tunings
#

send_buffer=128000
receive_buffer=1048576

if [ $(($(ipadm show-prop -c -o current -p ${send_buffer} tcp)+0)) -lt ${send_buffer} ]; then
  ipadm set-prop -p send_maxbuf=128000 tcp
fi

if [ $(($(ipadm show-prop -c -o current -p ${receive_buffer} tcp)+0)) -lt ${receive_buffer} ]; then
  ipadm set-prop -p recv_maxbuf=1048576 tcp
fi

exit 0
