#!/bin/bash
#
# Create an image and manifest out of a shut down zone.  The zone
# should have been prepared with sm-prepare-image.
#

if [ $# -ne 2 ]; then
	echo "usage: $0 <name> <zone>" >&2
	exit 2
else
	name=$1; shift
	zone=$1; shift
fi

set -e

outdir="$(dirname $0)/output"

read -p 'Enter description: ' description
read -p 'Enter homepage: ' homepage

if [ -z "${description}" ]; then
	echo "WARNING: No description entered.  Edit ${outdir}/${name}.json"
	echo "when this script finishes."
fi

if [ -z "${homepage}" ]; then
	echo "WARNING: No homepage entered.  Edit ${outdir}/${name}.json"
	echo "when this script finishes."
fi

echo "Taking snapshot ..."
zfs snapshot zones/${zone}@snap$$
echo "Sending snapshot to ${outdir}/${name}.zfs.gz ..."
zfs send zones/${zone}@snap$$ | gzip -9 >${outdir}/${name}.zfs.gz
zfs destroy zones/${zone}@snap$$

echo "Creating ${outdir}/${name}.json ..."
sha1=$(digest -a sha1 ${outdir}/${name}.zfs.gz)
size=$(ls -l ${outdir}/${name}.zfs.gz | awk '{print $5}')
uuid=$(uuid)
datestamp=$(date '+%FT%TZ')

cat $(dirname $0)/imgjson.in \
  | sed -e "s!@NAME@!${name%-*}!g" \
        -e "s!@VERSION@!${name##*-}!g" \
        -e "s!@DATESTAMP@!${datestamp}!g" \
        -e "s!@DESCRIPTION@!${description}!g" \
        -e "s!@HOMEPAGE@!${homepage}!g" \
        -e "s!@SHA1@!${sha1}!g" \
        -e "s!@SIZE@!${size}!g" \
        -e "s!@UUID@!${uuid}!g" \
  >${outdir}/${name}.json

echo "Done.  Now run this to install the image:"
echo ""
echo "  imgadm install -m ${outdir}/${name}.json -f ${outdir}/${name}.zfs.gz"
echo ""
