#!/bin/bash

set -eu

usage()
{
	echo "usage: $0 [-hlm] -b <branch> [-d <date>] -r <release>" >&2
	exit 1
}

lts=""
bflag=false
dflag=""
mflag=false
rflag=false

while getopts ":b:d:hlmr:" flag; do
	case "${flag}" in
	b) bflag=true; branch=$OPTARG ;;
	d) dflag="-d $OPTARG" ;;
	l) lts="-lts" ;;
	m) mflag=true ;;
	r) rflag=true release=$OPTARG ;;
	v) verbose=1 ;;
	z) zone=$OPTARG ;;
	h) usage; exit ;;
	*) usage; exit 2 ;;
	esac
done
shift $((OPTIND - 1))

#
# Sanity checks.
#
if ! ${bflag} || ! ${rflag}; then
	usage
	exit 2
fi

case "${branch}" in
201[0-5]Q[1-4]|2016Q[1-3])
	# 20141030
	seed_uuid="d135c918-0558-11e5-bccb-9bb2e57508ee"
	;;
2016Q4|201[7-9]Q[1-4]|20[2-9][0-9]Q[1-4])
	# 20141030u1 (DATASET-1240)
	seed_uuid="88a04a6c-d413-11e6-8341-ff5fa45bf3e9"
	;;
esac

createimage()
{
	arch=$1; shift
	image=$1; shift
	
	echo "Creating proto zone."
	vmadm create <<-EOF
		{
		  "brand": "joyent",
		  "image_uuid": "${seed_uuid}",
		  "max_physical_memory": 512,
		  "alias": "proto-zone",
		  "resolvers": [
		    "192.168.1.1"
		  ],
		  "nics": [
		    {
		      "nic_tag": "admin",
		      "ip": "dhcp"
		    }
		  ]
		}
	EOF
	uuid=$(vmadm list -po uuid alias=proto-zone)
	if ${mflag}; then
		echo "Using master pkgsrc.joyent.com hosts entry."
		echo -e "72.2.118.211\tpkgsrc.joyent.com" >>"/zones/${uuid}/root/etc/hosts"
	fi
	echo "Creating ${image} zone."
	./install-base -c ${branch}-${arch} ${dflag} -n ${image} -r ${release} -z ${uuid}
	echo "Creating ${image}-${release} image."
	./create-image ${image}-${release} ${uuid}
	echo "Deleting proto zone."
	vmadm delete ${uuid}
}

createimage i386 minimal-32${lts}
createimage x86_64 minimal-64${lts}
createimage multiarch minimal-multiarch${lts}
createimage i386 base-32${lts}
createimage x86_64 base-64${lts}
createimage multiarch base-multiarch${lts}
createimage x86_64 pkgbuild
